# Generated by Django 3.0.6 on 2020-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynewsletter',
            name='body',
        ),
        migrations.AddField(
            model_name='mynewsletter',
            name='body_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mynewsletter',
            name='footer_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mynewsletter',
            name='header_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
