# Generated by Django 3.0.6 on 2020-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200609_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynewsletter',
            name='footer_content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mynewsletter',
            name='header_content',
            field=models.CharField(max_length=500),
        ),
    ]
