# Generated by Django 3.0.6 on 2020-06-09 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0003_auto_20200609_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterDispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.MyNewsletter')),
                ('receiver_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
