# Generated by Django 3.0.6 on 2020-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterdispatcher',
            name='receiver_list',
            field=models.ManyToManyField(to='subscriber.MySubscriber'),
        ),
    ]
